import "../stylesheets/admin/admin.scss"
import "popper.js"
import "jquery"
import "bootstrap"
import "../stylesheets/admin/material-dashboard.css"
import "../stylesheets/admin/demo.css"
import "packs/demo.js"
import "packs/material-dashboard.js"
